### ISSUE TITLE
Cannot download the BIOS file from Lenovo

### ISSUE THREAD

**Issue by zorbas78** [vovan47/miix310#3]
Hi Vlad / vovan47, 

tried to download the 44 bios from lenovo (https://download.lenovo.com/consumer/mobiles/1hcn44ww.exe), gives me a 404. I was wondering if you have the file still, if so please send it to me or put it here... Thanks

**Comment by zorbas78** [comment]
Help is appreciated by @ramsonline @sumpurns @wishvaherath @zqm64

**Comment by vovan47** [comment]
Hello @zorbas78, I briefly googled it (query: lenovo 1hcn44ww.exe) and found some sites where users uploaded it, like [4PDA forum](https://4pda.ru/forum/index.php?showtopic=786672&view=findpost&p=82511393). But I don't endorse you using that file and I don't guarantee in any way that it might work.
I think you can also contact Lenovo support somehow and ask them for it. 
Actually, [the official page](https://support.lenovo.com/ru/en/downloads/ds112922-bios-update-for-windows-10-64-bit-miix-310-10icr) has checksums for bios files, it's **a very good idea to validate your downloads** against them.

Good luck

**Comment by zorbas78** [comment]
Hey Vovan, 

I cannot come into 4PDA forum, tried it before as I cannot pass the captcha which gives some strings that are most likey russian numbers kyrillian and i cannot speak russian. 

Contacted Lenovo some days ago, no response yet. 

Thanks for your help! @vovan47

**Comment by eckad158** [comment]
🤷

**Comment by zorbas78** [comment]
@ramsonline thank you! downloaded the file, and verified it versus md5 checksum (no offense).
Thanks a lot. 

@vovan47 I will try to get in touch with Lenovo, so that they put the file back online. Then this manual here will work again. Once done I will close this issue. 

Have a nice week :)

**Comment by vovan47** [comment]
Ok, sorry for confusion with russian captcha, just let us know, in case if Lenovo will not provide the file back, I guess we could upload it here on Github as .tar.gz archive with a disclaimer, hopefully it will not violate any rules.

Cheers

**Comment by zorbas78** [comment]
> Ok, sorry for confusion with russian captcha, just let us know, in case if Lenovo will not provide the file back, I guess we could upload it here on Github as .tar.gz archive with a disclaimer, hopefully it will not violate any rules.
> 
> Cheers

...or copyrights. I'll keep you in the loop!

**Comment by zorbas78** [comment]
Hello, i have tried to talk to Lenovo support, and failed. They did not _understand_ the topic, or the fact, that they have a dead link on their support site. Instead they offered me the 320 MIIX Bios. Which is of course the wrong one, and should not be used. 

So if ANYONE requires the Update-file, please let me know. 

thanks
zorbas78
